<a href="https://colab.research.google.com/github/theabdulbasitt/pytorch_tutorial/blob/main/pytorch1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import torch
import numpy as np



# **Tensors**





Tensors are a specialized data structure that are very similar to arrays and matrices. In PyTorch, we use tensors to encode the inputs and outputs of a model, as well as the model’s parameters.

Tensors are similar to NumPy’s ndarrays, except that tensors can run on GPUs or other hardware accelerators. In fact, tensors and NumPy arrays can often share the same underlying memory, eliminating the need to copy data.



In [ ]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 1.6939,  0.5830,  0.6744,  0.2328],
        [ 0.3609,  0.4045,  0.1440,  0.4990],
        [-0.3772, -0.7619,  0.2072,  2.4681]])

In [ ]:
tensor_2d.dtype

torch.float32

In [ ]:
tensor_3d = torch.zeros(2,3,3)
tensor_3d

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [ ]:
var = torch.arange(10)
var

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
var =var.reshape(2,-1)
var


tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
var =  torch.arange(10)
var

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
var = var.view(2,5)
var

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

# **Simple  Neural Network**

In [ ]:
import torch.nn as nn
import torch.nn.functional as F

In [ ]:
# Creating a Model class  that inherits nn.Module
class Model(nn.Module):
  # input layer (4 features of the flower) -->
  # Hidden Layer1 (number of neurons) -->
  # H2 (n)  -->
  # output

  def __init__(self, in_features=4, h1=8, h2=9, out_features=3):
    super().__init__() # initiate or nn.Module
    self.fc1 = nn.Linear(in_features, h1)
    self.fc2 = nn.Linear(h1, h2)
    self.out = nn.Linear(h2, out_features)

  def forward(self, x):
    x = F.relu(self.fc1(x))
    x = F.relu(self.fc2(x))
    x = self.out(x)
    return x



In [ ]:
# pick a manual seed for randomaization
torch.manual_seed(41)
# creating an instance of our model
model = Model()

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
url = 'https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/0e7a9b0a5d22642a06d3d5b9bcbad9890c8ee534/iris.csv'
df = pd.read_csv(url)
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [ ]:
# converting label from strings to numbers

df['species'] = df['species'].replace({'setosa':0, 'versicolor':1, 'virginica':2})
df['species'].unique()

<ipython-input-7-197a712e78b2>:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['species'] = df['species'].replace({'setosa':0, 'versicolor':1, 'virginica':2})


array([0, 1, 2])

In [ ]:
x = df.drop('species',axis=1)
y = df['species']


In [ ]:
# converting x and y to numpy arrays

x = x.values
y = y.values

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
# train test split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)

In [ ]:
# converting fetures and label (train, test both ) into tensors

x_train = torch.FloatTensor(x_train)
x_test = torch.FloatTensor(x_test)

y_train = torch.LongTensor(y_train)
y_test = torch.LongTensor(y_test)

In [15]:
 # seting the criterion of model to measure the erorr, how far of the predictios are from the data

criterion = nn.CrossEntropyLoss()

# chossing Adam Optimizer and learning rate ( lr )

optimizer = torch.optim.Adam(model.parameters(), lr = 0.01)



In [16]:
# train model
epochs =100
losses = []

for i in range(epochs):
  # go forward and get prediction
  y_pred = model.forward(x_train)
  # measure loss
  loss = criterion(y_pred, y_train)
  # keep track of loss for concept understadning purpose
  losses.append(loss.detach().numpy())


  if i % 10 == 0:
    print(f'Epoch: {i} Loss: {loss}')

  #Do some back propogation: take the error rate of forward propogation and feed it back
  # through  the network to fine tune weights

  optimizer.zero_grad()
  loss.backward()
  optimizer.step()


Epoch: 0 Loss: 1.123980164527893
Epoch: 10 Loss: 1.026330590248108
Epoch: 20 Loss: 0.8561798334121704
Epoch: 30 Loss: 0.6227018237113953
Epoch: 40 Loss: 0.42110538482666016
Epoch: 50 Loss: 0.28016823530197144
Epoch: 60 Loss: 0.18531975150108337
Epoch: 70 Loss: 0.1269538700580597
Epoch: 80 Loss: 0.09192601591348648
Epoch: 90 Loss: 0.07171893864870071
