<a href="https://colab.research.google.com/github/theabdulbasitt/pytorch_tutorial/blob/main/pytorch1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np



# **Tensors**





Tensors are a specialized data structure that are very similar to arrays and matrices. In PyTorch, we use tensors to encode the inputs and outputs of a model, as well as the model’s parameters.

Tensors are similar to NumPy’s ndarrays, except that tensors can run on GPUs or other hardware accelerators. In fact, tensors and NumPy arrays can often share the same underlying memory, eliminating the need to copy data.



In [3]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 1.6939,  0.5830,  0.6744,  0.2328],
        [ 0.3609,  0.4045,  0.1440,  0.4990],
        [-0.3772, -0.7619,  0.2072,  2.4681]])

In [5]:
tensor_2d.dtype

torch.float32

In [6]:
tensor_3d = torch.zeros(2,3,3)
tensor_3d

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [7]:
var = torch.arange(10)
var

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
var =var.reshape(2,-1)
var


tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [11]:
var =  torch.arange(10)
var

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
var = var.view(2,5)
var

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])