<a href="https://colab.research.google.com/github/theabdulbasitt/pytorch_tutorial/blob/main/pytorch1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np



# **Tensors**





Tensors are a specialized data structure that are very similar to arrays and matrices. In PyTorch, we use tensors to encode the inputs and outputs of a model, as well as the model’s parameters.

Tensors are similar to NumPy’s ndarrays, except that tensors can run on GPUs or other hardware accelerators. In fact, tensors and NumPy arrays can often share the same underlying memory, eliminating the need to copy data.



In [ ]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 1.6939,  0.5830,  0.6744,  0.2328],
        [ 0.3609,  0.4045,  0.1440,  0.4990],
        [-0.3772, -0.7619,  0.2072,  2.4681]])

In [ ]:
tensor_2d.dtype

torch.float32

In [ ]:
tensor_3d = torch.zeros(2,3,3)
tensor_3d

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [ ]:
var = torch.arange(10)
var

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
var =var.reshape(2,-1)
var


tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
var =  torch.arange(10)
var

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
var = var.view(2,5)
var

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

# **Simple  Neural Network**

In [ ]:
import torch.nn as nn
import torch.nn.functional as F

In [ ]:
# Creating a Model class  that inherits nn.Module
class Model(nn.Module):
  # input layer (4 features of the flower) -->
  # Hidden Layer1 (number of neurons) -->
  # H2 (n)  -->
  # output

  def __init__(self, in_features=4, h1=8, h2=9, out_features=3):
    super().__init__() # initiate or nn.Module
    self.fc1 = nn.Linear(in_features, h1)
    self.fc2 = nn.Linear(h1, h2)
    self.out = nn.Linear(h2, out_features)

  def forward(self, x):
    x = F.relu(self.fc1(x))
    x = F.relu(self.fc2(x))
    x = self.out(x)
    return x



In [ ]:
# pick a manual seed for randomaization
torch.manual_seed(41)
# creating an instance of our model
model = Model()